---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pyscreen.fullname" . }}-clusterrole
  labels:
    app.kubernetes.io/name: {{ template "pyscreen.name" . }}
    helm.sh/chart: {{ template "pyscreen.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]