---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pyscreen.fullname" . }}-rbac
  labels:
    app.kubernetes.io/name: {{ template "pyscreen.name" . }}
    helm.sh/chart: {{ template "pyscreen.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pyscreen.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pyscreen.fullname" . }}-clusterrole