---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pyscreen.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ template "pyscreen.name" . }}
    helm.sh/chart: {{ template "pyscreen.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}